[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "public"

[dev]
  port = 8888

[[redirects]]
  from = "/oauth/callback"
  to = "/.netlify/functions/auth-callback"
  status = 200

[build.environment]
  NODE_VERSION = "18"
